#!/usr/bin/env bash

action=$1
shift

echo "todo value $todo"

[ "$action" = "usage" ] && {
  echo ""
  echo "  Remind:"
  echo "    $TODO_SH remind ITEM# DATE TIME"
  echo "      create a reminder out of the todo item with an alert time"
  echo ""
  exit 0
}

case "$1" in
[0-9]*)
    getTodo "$1"
    alert_date=$(date -j -f "%Y-%m-%d" "+%m/%d/%Y" "$2")
    alert_time=$(date -j -f "%H:%M" "+%I:%M%p" "$3")

### Original functionality
#$TODO_SH append "$1" "#reminded"

### AC patch to put due back at the end of the line
### get due:date values and store in a variable
TODO_MESSAGE=$(echo "$todo" | awk -F"due:" '{print $1}' | sed 's/([A-Z]) //g')
TODO_DUE_DATE=$(echo "$todo" | awk -F"due:" '{print "due:"$2}')
FINAL_TODO_MESSAGE="$TODO_MESSAGE #reminded $TODO_DUE_DATE"

$TODO_SH replace "$1" "$FINAL_TODO_MESSAGE"

echo "$todo + $alert_date + $alert_time"
osascript - "$todo" "$alert_date" "$alert_time" <<END
on run argv
    set stringedAll to date (item 2 of argv & " " & item 3 of argv)
    tell application "Reminders"
    tell list "Reminders" of default account
        make new reminder with properties {name:item 1 of argv, remind me date:stringedAll}
    end tell
    end tell
end run
END
;;
*)
    echo "Usage: $TODO_SH remind ITEM# DATE TIME"
esac
