#!/bin/bash

# Copyright (c) 2013 Duncan Eastoe <duncaneastoe@gmail.com> {{{

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. }}}
#***  Debugging on/off {{{
#set -x
#trap read debug
#*** }}}

## Display usage information ## {{{

function usage {
  echo ""
  echo " revive - Restore tasks from done.txt"
  echo
  echo " Usage:"
  echo "     revive"
  echo "         List available todos to revive (ie. done.txt)"
  echo
  echo "     revive ITEM#"
  echo "         Revive specified todo"
  echo ""
  exit 0
}

#*** }}}

## Lists completed todos in done.txt ## {{{

function listAvailableTodos {
    $TODO_FULL_SH listfile "$TODO_DIR/done.txt"

    exit 0
}

#*** }}}

## Copies todo from done.txt back to todo.txt ## {{{

function reviveTodo {
    getTodo "$1" "$TODO_DIR/done.txt"
    echo "$1"
    cleanTodo=$(echo "$1" | sed -E 's/x [0-9]{4}-[0-9]{2}-[0-9]{2} //')
    $TODO_FULL_SH add "$cleanTodo"

    exit 0
}

#*** }}}

#*** MAIN {{{

if [ "$1" == "usage" ]; then
  usage
fi

shift

if [ -z "$1" ]; then
    listAvailableTodos
elif [[ "$1" =~ [0-9]+ ]]; then
    reviveTodo "$1"
else
    usage
fi

exit 0

#*** }}}
